### ISSUE TITLE
TODO: Correlation Analysis

### ISSUE THREAD

**Issue by rohangoel96** [prasadtalasila/IRCLogParser#168]
1. Channel Profile
    - [ ] a) activity graph ---> based on busy times of the current time period (a month), predict the busy times of next time period one row is message bins for one time period (a month) with second being message bins for next time period.
    - [x] b) conversation characteristics ---> provide statistical distribution as illustrated by box plot for RT, CL, CRT parameters

2. Network Profile
    - [x] a) degree distribution  ---> provide a statistical distribution of coefficients of the curve fit equations
    - [ ] b) community detection ----> overlap percentages on communities detected over sequential time periods

3. User Profile
    - [x] a) keyword digest ----> overlap percentages on communities detected over sequential time periods
    - [x] b) HITS vs TF-IDF algos ----> overlap percentages on communities detected by the two methods

**Comment by rohangoel96** [comment]
@prasadtalasila @kaushik-rohit not sure what is meant by 'overlap percentages' and what methodology is wanted in 2b) 3a) 3b). Would be very helpful if someone could please elaborate on this if you guys have discussed on the same already?

**Comment by prasadtalasila** [comment]
Let results of a variable (say keywords) for month-1 be represented as set M1 and for month-2 be represented as set M2.
M12 = set of common elements between M1 and M2.

The overlap percentage = |M12| * 100 / |M1|

**Comment by rohangoel96** [comment]
@prasadtalasila thanks.I actually was more concerned about 'over sequential time periods' esp in 2B)

**Comment by rohangoel96** [comment]
@prasadtalasila thanks for the explanation. But for 3b) HITS is used for finding experts and tf-idf was submodule in keywords so I am not sure how we are to find overlap between communities because neither of them detected 'communities' as such,.

**Comment by prasadtalasila** [comment]
@rohangoel96 You are right. Let's turn HITS and TF-IDF keywords into a prediction mechanism for sequential time periods.

Thus the work on HITS and TF-IDF would be similar to activity graph.

Thanks for pointing out the discrepancy.

**Comment by rohangoel96** [comment]
@prasadtalasila, I am extremely sorry but I still don't understand what you exactly mean.

**Comment by prasadtalasila** [comment]
I am suggesting that HITS and TF-IDF should be done in a similar manner to 3a and 1a.

We take HITS results of January-2013 (M1) and February-2013 (M2). And then compute the overlap percentage as described before in this issue thread.

**Comment by rohangoel96** [comment]
Oh alright. And do we want to iterate?
1) Jan - Feb. Feb - March. March - April..... 
2) Jan - Feb. Jan - March. Jan-April or do we want want the overlap percentages for all the  12C2 combinations.
I guess 1) makes sense as we are aiming for sequential time periods?

**Comment by prasadtalasila** [comment]
We are undertaking correlation analysis at this point to show the relevance of measures chosen in analysis framework. A rigorous, long-time horizon analysis with robust predictors can wait for a future publication. Let's do it for Jan-Feb 2013 and Feb-March 2013. Lets see if the evidence is convincing enough for these two cases.

**Comment by rohangoel96** [comment]
Sure. I'll just try this and send the results across. I'm however doubtful of this giving anything significant because the users will change every month hence, minimum overlap. Anyways, let's see.

**Comment by rohangoel96** [comment]
My bad, the results are interesting. Sending in a mail soon.

**Comment by rohangoel96** [comment]
1b) 2a) done via 65489dc6b4dd3f947a635820eba078726353566c

**Comment by rohangoel96** [comment]
3a) 3b) via a82965dab9df1dcad3bc7345d4f8ae74bd955f78

**Comment by prasadtalasila** [comment]
@rohangoel96 Given the probabilistic nature of Infomaps community detection, it may be better to show the consistency of Infomaps code length rather than overlap percentages of the communities discovered over sequential time periods. 

What I am really suggesting is to convert 2b into box plot that is similar to 1b.

**Comment by prasadtalasila** [comment]
For 1a) a simple predictability metric would be correlation between the vectors of bin totals between two consecutive time periods.

For a month, take the message bin totals for each hour. The present message bins code on dev branch already computes for 24 hours of day. Totals obtained for a month form 24-element vector. We can get a similar 24-element vector for consecutive month. On these two vectors, we perform correlation and see the result.

**Comment by rohangoel96** [comment]
@prasadtalasila sure. That seems like a nice idea. For calculating correlation between those vectors, is pearson coefficient a good measure or are we looking for something else?

**Comment by prasadtalasila** [comment]
Pearson coefficient would do.

**Comment by rohangoel96** [comment]
@prasadtalasila  kindly check the results and close this issue  and merge #180

**Comment by prasadtalasila** [comment]
I launched the ubuntu.py driver on the server. As soon as its done, I will cross-check the results and close this issue.
In the mean time, please look at the issue #183.
